#!/bin/bash

SIMPLE_INTEGER_REGEXP="(0|-?[1-9]\d*)"
PARTED_INTEGER_REGEXP="[1-9]\d{0,2}(\,\d\d\d)*"

NUMBER_REGEXP="($SIMPLE_INTEGER_REGEXP|$PARTED_INTEGER_REGEXP)(\.\d+)?(e$SIMPLE_INTEGER_REGEXP)?"

EXPRESSION_REGEXP="^$NUMBER_REGEXP(\ *[\+\-\*\/]\ *$NUMBER_REGEXP)*$"
grep -Ps "$EXPRESSION_REGEXP"

