#!/bin/bash

DAY_REGEXP="(0[1-9]|[12]\d|30|31)"
MONTH_REGEXP="(0[1-9]|11|12)"
YEAR_SHORT_REGEXP="\d\d"
YEAR_LONG_REGEXP="\d\d\d\d"

DATE1_REGEXP="$DAY_REGEXP\.$MONTH_REGEXP\.$YEAR_SHORT_REGEXP"
DATE2_REGEXP="$DAY_REGEXP\.$MONTH_REGEXP\.$YEAR_LONG_REGEXP"
DATE3_REGEXP="$MONTH_REGEXP\/$DAY_REGEXP\/$YEAR_SHORT_REGEXP"
DATE4_REGEXP="$MONTH_REGEXP\/$DAY_REGEXP\/$YEAR_LONG_REGEXP"
DATE5_REGEXP="$YEAR_LONG_REGEXP\/$MONTH_REGEXP\/$DAY_REGEXP"

DATE_REGEXP="($DATE1_REGEXP|$DATE2_REGEXP|$DATE3_REGEXP|$DATE4_REGEXP|$DATE5_REGEXP)"

HOUR_REGEXP="([01]\d|2[0123])"
MIN_SEC_REGEXP="[0-5]\d"

TIME1_REGEXP="$HOUR_REGEXP\:$MIN_SEC_REGEXP"
TIME2_REGEXP="$HOUR_REGEXP\:$MIN_SEC_REGEXP\:$MIN_SEC_REGEXP"

TIME_REGEXP="($TIME1_REGEXP|$TIME2_REGEXP)"

TIME_DATE_REGEXP="\ *$TIME_REGEXP\ +$DATE_REGEXP\ *"
DATE_TIME_REGEXP="\ *$DATE_REGEXP\ +$TIME_REGEXP\ *"
FULL_DATE_REGEXP="^($TIME_DATE_REGEXP|$DATE_TIME_REGEXP|$DATE_REGEXP)$"

grep -Ps "$FULL_DATE_REGEXP"
